name: Send Manual Email

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Email subject'
        required: true
        default: 'Hello from GitHub Actions'
      body:
        description: 'Email body content'
        required: true
        default: 'Hello Sir,\n\nHow are you?\n\nBest regards,\nYour Team'
      attachment:
        description: 'Attachment file name (optional)'
        required: false
        default: 'demo.txt'

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pyopenssl
        
      - name: Create demo file if needed
        run: |
          if [ "${{ github.event.inputs.attachment }}" = "demo.txt" ]; then
            echo "This is a demo attachment file created by GitHub Actions." > demo.txt
            echo "Timestamp: $(date)" >> demo.txt
          fi
        
      - name: Send email
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python mail.py \
            --to "${{ secrets.EMAIL }}" \
            --subject "${{ github.event.inputs.subject }}" \
            --body "${{ github.event.inputs.body }}" \
            --attachment "${{ github.event.inputs.attachment }}"
